services:
  - type: web
    name: camrent-backend
    env: node
    plan: free
    rootDir: backend
    buildCommand: npm install
    startCommand: npm run start
    autoDeploy: true
    envVars:
      - key: NODE_VERSION
        value: 22
      - key: MONGODB_URI
        sync: false
      - key: JWT_SECRET
        sync: false
      - key: CLOUDINARY_CLOUD_NAME
        sync: false
      - key: CLOUDINARY_API_KEY
        sync: false
      - key: CLOUDINARY_API_SECRET
        sync: false
