import { Button } from '@/src/components/ui';
import type { AppPage } from '@/src/types/app';

interface AboutPageProps {
  onNavigate: (page: AppPage) => void;
}

export function AboutPage({ onNavigate }: AboutPageProps) {
  return (
    <div className="container mx-auto px-4 py-10">
      <div className="mx-auto max-w-4xl space-y-8">
        <div className="space-y-3">
          <h1 className="text-4xl font-extrabold tracking-tight">About CamRent PH</h1>
          <p className="text-muted-foreground">
            CamRent PH is a camera rental operations platform. It helps store owners manage inventory, bookings, records, and fraud alerts in one centralized system.
          </p>
          <div>
            <Button variant="outline" onClick={() => onNavigate('home')}>
              Back to Home
            </Button>
          </div>
        </div>

        <section className="space-y-3 rounded-xl border bg-card p-5">
          <h2 className="text-xl font-semibold">Platform Purpose</h2>
          <p className="text-sm text-muted-foreground">
            CamRent PH is a platform service. It has no physical products and currently has no direct payment integration. Payment automation is planned, but legal and operational paperwork is still in progress.
          </p>
          <p className="text-sm text-muted-foreground">
            For now, stores may continue using their social media pages for marketing while using CamRent PH for inventory tracking, order handling, fraud management, and rental workflow organization.
          </p>
        </section>

        <section className="space-y-3 rounded-xl border bg-card p-5">
          <h2 className="text-xl font-semibold">Fraud Protection Focus</h2>
          <p className="text-sm text-muted-foreground">
            A key feature of CamRent PH is fraud monitoring. Store owners can report suspicious renters internally and escalate to global fraud warnings subject to review and investigation.
          </p>
          <p className="text-sm text-muted-foreground">
            Fraud reporting is treated as high priority because the platform is designed for rental business owners who need better structure and risk control in daily operations.
          </p>
        </section>

        <section className="space-y-3 rounded-xl border bg-card p-5">
          <h2 className="text-xl font-semibold">For Customers and Stores</h2>
          <p className="text-sm text-muted-foreground">
            Customers can keep rental history and receive vouchers from participating stores. Vouchers are generated by stores and are governed by each store&apos;s own policy.
          </p>
          <p className="text-sm text-muted-foreground">
            The core mission is to solve inventory management and scam prevention in camera rentals while improving traceability for both parties.
          </p>
        </section>

        <section className="space-y-3 rounded-xl border bg-card p-5">
          <h2 className="text-xl font-semibold">Founder</h2>
          <p className="text-sm text-muted-foreground">
            CamRent PH was founded by mrHeinrichhh, a software developer passionate about solving practical problems in the local community.
          </p>
          <a className="text-sm font-medium underline" href="https://mrheinrich.vercel.app" target="_blank" rel="noreferrer">
            Visit Founder Profile
          </a>
        </section>
      </div>
    </div>
  );
}
