import { Button } from '@/src/components/ui';
import type { AppPage } from '@/src/types/app';

interface AboutPageProps {
  onNavigate: (page: AppPage) => void;
}

export function AboutPage({ onNavigate }: AboutPageProps) {
  return (
    <div className="min-h-screen bg-[var(--tone-bg)] px-4 py-10">
      <div className="container mx-auto max-w-4xl space-y-8">
        <div className="rounded-3xl border border-slate-200 bg-white p-6 shadow-sm sm:p-8">
          <p className="text-xs uppercase tracking-[0.3em] text-slate-400">CamRent PH</p>
          <h1 className="mt-2 text-3xl font-semibold text-slate-900 sm:text-4xl">About CamRent PH</h1>
          <p className="mt-2 text-sm text-slate-500">
            CamRent PH is a camera rental operations platform. It helps store owners manage inventory, bookings, records, and fraud alerts in one centralized system.
          </p>
          <div className="mt-4">
            <Button variant="outline" className="rounded-full" onClick={() => onNavigate('home')}>
              Back to Home
            </Button>
          </div>
        </div>

        <section className="space-y-3 rounded-3xl border border-slate-200 bg-white p-6 shadow-sm">
          <h2 className="text-lg font-semibold text-slate-900">Platform Purpose</h2>
          <p className="text-sm text-slate-500">
            CamRent PH is a platform service. It has no physical products and currently has no direct payment integration. Payment automation is planned, but legal and operational paperwork is still in progress.
          </p>
          <p className="text-sm text-slate-500">
            For now, stores may continue using their social media pages for marketing while using CamRent PH for inventory tracking, order handling, fraud management, and rental workflow organization.
          </p>
        </section>

        <section className="space-y-3 rounded-3xl border border-slate-200 bg-white p-6 shadow-sm">
          <h2 className="text-lg font-semibold text-slate-900">Fraud Protection Focus</h2>
          <p className="text-sm text-slate-500">
            A key feature of CamRent PH is fraud monitoring. Store owners can report suspicious renters internally and escalate to global fraud warnings subject to review and investigation.
          </p>
          <p className="text-sm text-slate-500">
            Fraud reporting is treated as high priority because the platform is designed for rental business owners who need better structure and risk control in daily operations.
          </p>
        </section>

        <section className="space-y-3 rounded-3xl border border-slate-200 bg-white p-6 shadow-sm">
          <h2 className="text-lg font-semibold text-slate-900">For Customers and Stores</h2>
          <p className="text-sm text-slate-500">
            Customers can keep rental history and receive vouchers from participating stores. Vouchers are generated by stores and are governed by each store&apos;s own policy.
          </p>
          <p className="text-sm text-slate-500">
            The core mission is to solve inventory management and scam prevention in camera rentals while improving traceability for both parties.
          </p>
        </section>

        <section className="space-y-3 rounded-3xl border border-slate-200 bg-white p-6 shadow-sm">
          <h2 className="text-lg font-semibold text-slate-900">Founder</h2>
          <p className="text-sm text-slate-500">
            CamRent PH was founded by mrHeinrichhh, a software developer passionate about solving practical problems in the local community.
          </p>
          <a className="text-sm font-medium underline" href="https://mrheinrich.vercel.app" target="_blank" rel="noreferrer">
            Visit Founder Profile
          </a>
        </section>
      </div>
    </div>
  );
}
